### ISSUE TITLE
Sending segment batch failed with: NoCredentialProviders: no valid provider

### ISSUE THREAD

**Issue by Hassan1175** [awsdocs/aws-xray-developer-guide#26]
I am running daemon locally for my Django project to get traces.
I have configured the credentials in environment variables and ~/.aws/credentials file as well. But still facing that issue. Can anybody please help me in figuring out issue.
The error which I am facing is

Sending segment batch failed with: NoCredentialProviders: no valid provider

**Comment by davikeog** [comment]
Hi! It looks like this issue was resolved successfully here: https://github.com/aws/aws-xray-daemon/issues/59.
