### ISSUE TITLE
Please clarify behavior of subsegment `http.request.traced` property, meaning of "broken" trace

### ISSUE THREAD

**Issue by jmm** [awsdocs/aws-xray-developer-guide#61]
Hello, the segment documents :: [HTTP request data](https://github.com/awsdocs/aws-xray-developer-guide/blob/cecd7963479304040ddcaab0be0f1a5175f5c60d/doc-source/xray-api-segmentdocuments.md#http-request-data) documentation says:

> `traced` – \(subsegments only\) **boolean** indicating that the downstream call is to another traced service\. If this field is set to `true`, X\-Ray considers the trace to be broken until the downstream service uploads a segment with a `parent_id` that matches the `id` of the subsegment that contains this block\.

1. Can you please clarify what "broken" means? What affect does it have on behavior? How would it be observable in the console or raw trace data?

1. What would be the effect of setting that on a subsegment for a request to a non-instrumented service that will never upload a segment?

See also:

https://github.com/aws/aws-xray-sdk-node/issues/493

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
