### ISSUE TITLE
Code example has SQL injection

### ISSUE THREAD

**Issue by nbcchen** [awsdocs/aws-xray-developer-guide#70]
https://github.com/awsdocs/aws-xray-developer-guide/blob/main/doc-source/xray-sdk-dotnet-sqlqueries.md?plain=1#L21

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
